# Rack middleware that stamps security response headers on EVERY response —
# dynamic pages, static assets, and error pages alike — so coverage doesn't
# depend on the controller stack (ASVS V14; ZAP 10021/10063/90004).
#
# Content-Security-Policy is intentionally NOT set here: it carries a
# per-request nonce generated by Rails (see config/initializers/
# content_security_policy.rb), so it stays on the dynamic responses only.
class SecurityHeaders
  PERMISSIONS_POLICY = [
    "accelerometer=()", "camera=()", "geolocation=()", "gyroscope=()",
    "magnetometer=()", "microphone=()", "payment=()", "usb=()"
  ].join(", ").freeze

  def initialize(app)
    @app = app
  end

  def call(env)
    status, headers, body = @app.call(env)
    headers["x-content-type-options"]      = "nosniff"
    headers["x-frame-options"]             = "SAMEORIGIN"
    headers["referrer-policy"]             = "strict-origin-when-cross-origin"
    headers["permissions-policy"]          = PERMISSIONS_POLICY
    headers["cross-origin-opener-policy"]  = "same-origin"
    headers["cross-origin-resource-policy"] = "same-origin"
    [ status, headers, body ]
  end
end
